import { type MobilyPurchaseSDKOptions } from './NativeMobilyflowReactNativeSdk';
import { MobilyProduct } from './models/product/mobily-product';
import { MobilySubscriptionGroup } from './models/product/mobily-subscription-group';
import { MobilyCustomerEntitlement } from './models/entitlement/mobily-customer-entitlement';
import { MobilyCustomer } from './models/mobily-customer';
import { PurchaseOptions } from './models/internal/purchase-options';
import { MobilyTransferOwnershipStatus } from './enums/mobily-transfer-ownership-status';
import { MobilyEvent } from './models/mobily-event';
import { MobilyRefundDialogResult } from './enums/mobily-refund-dialog-result';
export declare const MobilyPurchaseSDK: {
    initialize: (appId: string, apiKey: string, environment: string, options?: MobilyPurchaseSDKOptions) => void;
    close: () => void;
    login: (externalRef: string) => Promise<MobilyCustomer>;
    logout: () => Promise<void>;
    getProducts: (identifiers?: string[], onlyAvailable?: boolean) => Promise<MobilyProduct[]>;
    getSubscriptionGroups: (identifiers?: string[], onlyAvailable?: boolean) => Promise<MobilySubscriptionGroup[]>;
    getSubscriptionGroupById: (id: string) => Promise<MobilySubscriptionGroup>;
    getEntitlementForSubscription: (subscriptionGroupId: string) => Promise<MobilyCustomerEntitlement | null>;
    getEntitlement: (productId: string) => Promise<MobilyCustomerEntitlement | null>;
    getEntitlements: (productIds?: string[]) => Promise<MobilyCustomerEntitlement[]>;
    getExternalEntitlements: () => Promise<MobilyCustomerEntitlement[]>;
    requestTransferOwnership: () => Promise<MobilyTransferOwnershipStatus>;
    openManageSubscription: () => Promise<void>;
    openRefundDialogForProduct: (product: MobilyProduct) => Promise<MobilyRefundDialogResult>;
    openRefundDialogForTransactionId: (transactionId: string) => Promise<MobilyRefundDialogResult>;
    purchaseProduct: (product: MobilyProduct, options?: PurchaseOptions) => Promise<MobilyEvent>;
    sendDiagnostic: () => Promise<void>;
    getStoreCountry: () => Promise<string | null>;
    isBillingAvailable: () => Promise<boolean>;
    isForwardingEnable: (externalRef: string) => Promise<boolean>;
    getCustomer: () => Promise<MobilyCustomer>;
    getSDKVersion: () => Promise<string>;
};
//# sourceMappingURL=MobilyPurchaseSDK.d.ts.map